<?php
if ( !defined( 'ABSPATH' ) && !defined( 'WP_UNINSTALL_PLUGIN' ) ) {
exit();
} else {
delete_option('can_manage_events');
delete_option('my_calendar_style');
delete_option('display_author');
delete_option('display_jump');
delete_option('display_todays');
delete_option('display_upcoming');
delete_option('display_upcoming_days');
delete_option('my_calendar_version');
delete_option('display_upcoming_type');
delete_option('display_upcoming_events');
delete_option('display_past_days');
delete_option('display_past_events');
delete_option('my_calendar_use_styles');
delete_option('my_calendar_show_months');
delete_option('my_calendar_show_map');
delete_option('my_calendar_show_address');
delete_option('my_calendar_today_template');
delete_option('my_calendar_upcoming_template');
delete_option('my_calendar_today_title');
delete_option('my_calendar_today_widget_title');
delete_option('my_calendar_upcoming_widget_title');
delete_option('my_calendar_upcoming_title');
delete_option('my_calendar_today_template');
delete_option('display_upcoming_type');
delete_option('display_upcoming_days');
delete_option('display_upcoming_events');
delete_option('display_past_events');
delete_option('display_past_days');
delete_option('ko_calendar_imported');
delete_option('display_in_category');
delete_option('my_calendar_show_heading');
delete_option('my_calendar_listjs');
delete_option('my_calendar_caljs');
delete_option('calendar_javascript');
delete_option('list_javascript');
delete_option('my_calendar_minijs');
delete_option('mini_javascript');
delete_option('my_calendar_notime_text');
delete_option('my_calendar_hide_icons');
delete_option('my_calendar_caption');
delete_option('mc_event_link_expires');
delete_option('mc_apply_color');
delete_option('my_calendar_date_format');
delete_option('my_calendar_no_events_text');
delete_option('my_calendar_show_css');
delete_option('mc_apply_color');
delete_option('mc_next_events');
delete_option('mc_previous_events');
delete_option('mc_input_options');
delete_option('mc_input_options_administrators');
delete_option('mc_event_mail','false');
delete_option('mc_event_mail_subject');
delete_option('mc_event_mail_to');
delete_option('mc_event_mail_message');
delete_option('mc_event_approve');		
delete_option('mc_event_approve_perms');
delete_option('mc_no_fifth_week');		
delete_option('mc_user_settings');
delete_option( 'my_calendar_ajaxjs' );
delete_option( 'ajax_javascript' );
delete_option( 'my_calendar_templates');
delete_option( 'mc_user_settings_enabled');
delete_option( 'mc_user_location_type'); 
delete_option( 'my_calendar_show_js');
delete_option( 'mc_event_open');
delete_option( 'mc_event_closed');
delete_option( 'mc_event_registration');
delete_option( 'mc_short');
delete_option( 'mc_desc');
delete_option( 'mc_location_type');
delete_option( 'mc_skip_holidays_category');
delete_option( 'mc_skip_holidays');
delete_option( 'mc_event_edit_perms');
delete_option( 'my_calendar_widgets_defaults');
delete_option( 'my_calendar_css_file');
delete_option( 'mc_db_version');
delete_option( 'my_calendar_stored_styles');
delete_option('mc_show_rss');
delete_option('mc_show_ical');
delete_option( 'mc_show_weekends' );
delete_option( 'mc_uri' );
add_option( 'my_calendar_uninstalled','true' );

}
?>